#+OPTIONS: toc:nil todo:nil
#+PROPERTY: header-args:python :results output raw  :noweb no-export :exports code

* Preface
  We take material from the earlier lecture on the subistence diet
  problem, and use it to define the subsistence diet as a function of prices. 

  We need some particular versions of the following modules;
#+begin_src ipython :dir ./ :results silent
!pip install -r requirements.txt
#+end_src

  Define user and api key here:
  #+begin_src ipython :dir ./ :results silent :tangle diet_problem.py
user = "ligon"

# API key for Gov
apikey = {'ligon':"inIyO1begWSRqsYtxS7m6p09PSyq7Qiw7fxzV2qN"}

# File with private keys for relevant service account to authenticate
# and access google spreadsheets
serviceacct = {'ligon':'students-9093fa174318.json'}
  #+end_src


* Input Data 

The critical user input is a =pandas.DataFrame= with (at least)
these columns:

  - Food :: Label used to identify food
  - Quantity :: Amount of food
  - Units :: Units in which amounts of this food is measured
  - Price :: Price for quantity of food
  - FDC :: Key identifying food in the FoodDataCentral dataset.

** Using data from Google Sheets

#+begin_src ipython :tangle diet_problem.py
# ID of sheet and name of worksheet for google sheets.   
# Easiest if these are public (or use service accounts)

SHEETs = [# Stigler's foods, modern prices
          ("https://docs.google.com/spreadsheet/ccc?key=1ObK5N_5aVXzVHE7ZXWBg0kQvPS3k1enRwsUjhytwh5A","Table B"), 
         ]
#+end_src

#+results:
:results:
:end:


** Compile data on food prices

   For each sheet in the list =SHEETs= grab data and concatenate into
   a DataFrame.
#+begin_src ipython  :tangle diet_problem.py
import pandas as pd
from eep153_tools import read_sheets

df = pd.concat([read_sheets(spreadsheet,json_creds=serviceacct[user],sheet=sheet) for spreadsheet, sheet in SHEETs],
               ignore_index=True,sort=False)

#+end_src


** Look up nutritional information for foods

Now we have a list of foods with prices.  Do lookups on USDA database
to get nutritional information.

#+begin_src ipython :tangle diet_problem.py
import fooddatacentral as fdc

D = {}
count = 0
for food in  df.Food.tolist():
    try:
        FDC = df.loc[df.Food==food,:].FDC[count]
        count+=1
        D[food] = fdc.nutrients(apikey[user],FDC).Quantity
    except AttributeError: 
        warnings.warn("Couldn't find FDC Code %s for food %s." % (food,FDC))        

FoodNutrients = pd.DataFrame(D,dtype=float)
#+end_src

* Units & Prices

Now, the prices we observe can be for lots of different quantities and
units.  The FDC database basically wants everything in either hundreds
of grams (hectograms) or hundreds of milliliters (deciliters).  
We use the =units= function to convert all foods to either
deciliters or hectograms, to match FDC database:

#+begin_src ipython :results output raw :tangle diet_problem.py 
# Convert food quantities to FDC units
df['FDC Quantity'] = df[['Quantity','Units']].T.apply(lambda x : fdc.units(x['Quantity'],x['Units']))

# Now may want to filter df by time or place--need to get a unique set of food names.
df['FDC Price'] = df['Price']/df['FDC Quantity']

df.dropna(how='any') # Drop food with any missing data

# To use minimum price observed
Prices = df.groupby('Food',sort=False)['FDC Price'].min()
#+end_src

* Dietary Requirements

We've figured out some foods we can buy, the nutritional content of
those foods, and  the price of the foods.  Now we need to say
something about nutritional requirements.   Our data for this is based
on  US government recommendations available at
https://www.dietaryguidelines.gov/sites/default/files/2019-05/2015-2020_Dietary_Guidelines.pdf.

I've put some of these data into a google spreadsheet at
https://docs.google.com/spreadsheets/d/1y95IsQ4HKspPW3HHDtH7QMtlDA66IUsCHJLutVL-MMc/. 


#+begin_src ipython :results output raw :tangle diet_problem.py 
from eep153_tools import read_sheets

DRIs = "https://docs.google.com/spreadsheets/d/1y95IsQ4HKspPW3HHDtH7QMtlDA66IUsCHJLutVL-MMc/"

# Define *minimums*
diet_min = read_sheets(DRIs,json_creds=serviceacct[user],sheet='diet_minimums').set_index('Nutrition')

# Define *maximums*
diet_max = read_sheets(DRIs,json_creds=serviceacct[user],sheet='diet_maximums').set_index('Nutrition')

#+end_src

* Putting it together

Here we take the different pieces of the puzzle we've developed and
put them together in the form of a linear program we can solve.
Recall that the mathematical problem we're trying to solve is
\[
    \min_x c'x
\]
such that
\[
     Ax \geq b
\]
If we buy a bag of groceries with quantities given by $x$, the total
cost of the bag of groceries is the inner product of prices and
quantities.  Since we've converted our units above, this gives us a
vector of prices where quantities are all in 100 g or ml units.

The following code block defines a function 
#+begin_src ipython :results output raw :tangle diet_problem.py
from  scipy.optimize import linprog as lp
import numpy as np

def solve_subsistence_problem(FoodNutrients,Prices,diet_min,diet_max,tol=1e-6):
    """Solve Stigler's Subsistence Cost Problem.

    Inputs:
       - FoodNutrients : A pd.DataFrame with rows corresponding to foods, columns to nutrients.
       - Prices : A pd.Series of prices for different foods
       - diet_min : A pd.Series of DRIs, with index corresponding to columns of FoodNutrients,
                    describing minimum intakes.
       - diet_max : A pd.Series of DRIs, with index corresponding to columns of FoodNutrients,
                    describing maximum intakes.
       - tol : Solution values smaller than this in absolute value treated as zeros.
       
    """
    c = Prices.apply(lambda x:x.magnitude).dropna()

    # Compile list that we have both prices and nutritional info for; drop if either missing
    use = list(set(c.index.tolist()).intersection(FoodNutrients.columns.tolist()))
    c = c[use]

    # Drop nutritional information for foods we don't know the price of,
    # and replace missing nutrients with zeros.
    Aall = FoodNutrients[c.index].fillna(0)

    # Drop rows of A that we don't have constraints for.
    Amin = Aall.loc[diet_min.index]

    Amax = Aall.loc[diet_max.index]

    # Minimum requirements involve multiplying constraint by -1 to make <=.
    A = pd.concat([Amin,-Amax])

    b = pd.concat([diet_min,-diet_max]) # Note sign change for max constraints

    # Now solve problem!  (Note that the linear program solver we'll use assumes
    # "less-than-or-equal" constraints.  We can switch back and forth by
    # multiplying $A$ and $b$ by $-1$.)

    result = lp(c, -A, -b, method='interior-point')

    result.A = A
    result.b = b
    result.diet = pd.Series(result.x,index=c.index)

    return result
#+end_src

* Using =solve_subsistence_problem= to analyze diet

Let's choose a particular group (type of person with particular
dietary requirements) and solve the subsistence problem for them:
#+begin_src ipython :results output raw :tangle diet_problem.py
group = 'F 19-30'
tol = 1e-6

result = solve_subsistence_problem(FoodNutrients,Prices,diet_min[group],diet_max[group],tol=tol)

print("Cost of diet for %s is $%4.2f per day.\n" % (group,result.fun))

# Put back into nice series
diet = result.diet

print("\nDiet (in 100s of grams or milliliters):")
print(diet[diet >= tol])  # Drop items with quantities less than precision of calculation.
print()

tab = pd.DataFrame({"Outcome":np.abs(result.A).dot(diet),"Recommendation":np.abs(result.b)})
print("\nWith the following nutritional outcomes of interest:")
print(tab)
print()

print("\nConstraining nutrients are:")
excess = tab.diff(axis=1).iloc[:,1]
print(excess.loc[np.abs(excess) < tol*100].index.tolist())

#+end_src
  
* Effects of Price Changes on Subsistence Diet
  As prices change, we should expect the minimum cost diet to also
  change.  The code below creates a graph which changes prices away
  from the `base' case one food at a time, and plots changes in total
  diet cost.
#+begin_src ipython :tangle diet_problem.py
import cufflinks as cf
cf.go_offline()

scale = [.5,.6,.7,.8,.9,1.,1.1,1.2,1.3,1.4,1.5]
scale = [.5,1,2]

cost0 = solve_subsistence_problem(FoodNutrients,Prices,diet_min[group],diet_max[group],tol=tol).fun

Price_response={}
for s in scale:
    cost = {}
    for i,p in enumerate(Prices):
        my_p = Prices.copy()
        my_p[i] = p*s
        result = solve_subsistence_problem(FoodNutrients,my_p,diet_min[group],diet_max[group],tol=tol)
        cost[Prices.index[i]] = np.log(result.fun/cost0)
    Price_response[np.log(s)] = cost

Price_response = pd.DataFrame(Price_response).T
Price_response.iplot(xTitle='log price change',yTitle='log cost change')
#+end_src
