#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:{} arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK")
#+OPTIONS: date:t e:t email:nil f:t inline:t num:t p:nil pri:nil
#+OPTIONS: prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t
#+OPTIONS: toc:nil todo:t |:t
#+TITLE: The Minimum Cost Diet Problem
#+AUTHOR: Ethan Ligon
#+EMAIL: ligon@berkeley.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.1 (Org mode 9.2)

* Introduction
The idea of this project is to solve the problem of finding the
minimum cost diet satisfying a set of "Recommended Daily Allowances"
(RDAs) for a particular set of nutrients and possible kind of food.

** History 
This problem was first "solved" by cite:stigler45 for a set of foods
and prices and RDA requirements (see cite:dantzig90 for an
entertaining discussion of what "solved" meant in that context).
Times have changed: the variety of different kinds of food, food
prices, and RDA requirements are all quite different from what they
were for our grandparents.

** Dietary Guidelines
   A compilation of dietary guidelines are provided at
   https://health.gov/sites/default/files/2019-09/2015-2020_Dietary_Guidelines.pdf
   (See especially Appendix 7);
   these provide recommended levels of 31 different nutrients by age
   and sex. 


* The Model
 
Stigler's insight was  that the  minimum cost diet (MCD) problem was
most naturally posed as a [[https://en.wikipedia.org/wiki/Linear_programming][linear program]].  If there are $n$ different
kinds of food one can buy, represent quantities consumed of these as a
vector $x$.  Each kind of food has a corresponding price that the
consumer takes as given, call this vector of prices $p$. Then  the
cost of a consumer's diet is $p'x$, where the prime indicates the
inner or [[https://en.wikipedia.org/wiki/Dot_product][dot product]] of the two vectors.

Each unit of a given kind of food is assumed to provide a set of
nutrients, of the sort often reported on food labels.  If there are
$m$ nutrients, then let $A$ be a matrix with $m$ rows and $n$ columns
describing the nutritional content of a single unit of each of kind of
food.

There are various sources of recommendations regarding nutrition.
These can take the form of either equalities or inequalities.  For
example, it is recommended that females in their twenties consume 2000
kilo-calories, 46 grams of protein, and  28 grams of fiber per day,
but  less than 23 grams of sodium.  Then using the matrix notation
above, we can write these constraints as something like
\[
    Ax \geq \underline{b}
\]
where $\underline{b}$ is a vector of recommendations about /minimum/ amounts of
different nutrients.  Similarly, if there are some things we want to
make sure we eat /less/ of (e.g., mercury, sodium, calories), that can
be written as a set of linear inequalities
\[
    Ax \leq\bar{b},
\]
where $\bar{b}$ is a vector of recommendations about /maximum/ amounts
of different nutrients.  Note that this constraint can /also/ be
expressed as a greater than constraint by multiplying both sides by $-1$.

Note that if some some nutrients we want exact equalities these can be
specified by specifying both a greater-than and a less-than
constraint.

Putting this all together, the linear program to compute the minimum
cost diet looks like
\[
   \min_x p'x 
\]
such that
\[
   \begin{bmatrix}
      A\\
      -A
   \end{bmatrix}x \geq \begin{bmatrix}
                        \underline{b}\\
                        -\bar{b}
                      \end{bmatrix}.
\]

Solving problems like this by hand is generally difficult for more
than a few variables and constraints, but
numerical software has been developed that can handle large (millions)
of both variables and constraints.  There are a variety of different
implementations; the one we'll use in our prototype is part of the
=scipy.optimize= package.

* Inputs                                                           :noexport:

** Dietary Guidelines
   A compilation of dietary guidelines are provided at in an appendix of
https://www.dietaryguidelines.gov/sites/default/files/2021-03/Dietary_Guidelines_for_Americans-2020-2025.pdf
these provide recommended levels of 31 different nutrients by age and
sex.  I've put some of these data into a google spreadsheet at
https://docs.google.com/spreadsheets/d/1y95IsQ4HKspPW3HHDtH7QMtlDA66IUsCHJLutVL-MMc/.
We'll use these to construct the vector $b$.


** Nutritional content of different kinds of food

   A source for nutritional information for different kinds of food is
   provided by the USDA.  This will be used to construct the matrix $A$.

   Note that USDA dataset uses "FDC" codes to identify different
   kinds of foods; can also map FDC -> UPC for many (mostly processed) foods.
      - https://fdc.nal.usda.gov/;
      - here's documentation of the api: https://fdc.nal.usda.gov/api-guide.html
      - Here's the actual data:
         https://fdc.nal.usda.gov/download-datasets.html

** Foods, food prices, units
   This one is up to you!  You'll need to choose a set of candidate
   foods that might be used in the diet.  For each kind of food you'll
   also need to know its price and the units in which quantities of
   the foods are to be measured.


* References
#+LATEX: \renewcommand{\refname}{}\printbibliography

* Minimum Diet Cost Problem                                   :ignore:slides:
  :PROPERTIES:
  :EXPORT_OPTIONS: H:1
  :EXPORT_FILE_NAME: ../Materials/Project2/minimum_cost_diet_slides
  :END:
** Introduction
 The idea of this project is to solve the problem of finding the
 minimum cost diet satisfying a set of "Recommended Daily Allowances"
 (RDAs) for a particular set of nutrients and possible kind of food.

** History 
 - Problem first "solved" by cite:stigler45 for a set of foods
   and prices and RDA requirements (see cite:dantzig90 for an
   entertaining discussion of what "solved" meant in that context).

 - Times have changed: the variety of different kinds of food, food
   prices, and RDA requirements are all quite different from what they
   were for our grandparents.

** Dietary Guidelines
   A compilation of dietary guidelines are provided at in an appendix
of
https://www.dietaryguidelines.gov/sites/default/files/2021-03/Dietary_Guidelines_for_Americans-2020-2025.pdf
these provide recommended levels of 31 different nutrients by age and
sex.  I've put some of these data into a google spreadsheet at
https://docs.google.com/spreadsheets/d/1y95IsQ4HKspPW3HHDtH7QMtlDA66IUsCHJLutVL-MMc/.
We'll use these to construct the vector $b$.


** Diet Cost
 Stigler's insight was  that the  minimum cost diet (MCD) problem was
 most naturally posed as a [[https://en.wikipedia.org/wiki/Linear_programming][linear program]].
   - Suppose $n$ different kinds of food;
   - Represent quantities consumed of these as a /vector/ $x$ with $n$
     elements.  Many elements may be zero!
   - Each kind of food has price; call this vector of prices $p$. 

*** Total Cost
 A consumer's diet costs $p'x$, where the prime indicates the
 inner or [[https://en.wikipedia.org/wiki/Dot_product][dot product]] of the two vectors.

** Nutritional Recommendations
 Each unit of a given kind of food is assumed to provide a set of
 nutrients.
  - Suppose $m$ nutrients, then let $A$ be a matrix with $m$ rows and
    $n$ columns describing the nutritional content of a single unit of
    each of kind of food.

  - Different sources of "recommendations" regarding nutrition.
    - Equalities:
      A female in her twenties 'should' consume: 
       - 2000 kilo-calories
       - 46 grams of protein
       - 28 grams of fiber per day
  - Inequalities:
    - Less than 23 grams of sodium
** Matrix notation
 We can write these constraints as something like
 \[
     Ax \geq \underline{b}
 \]
 where $\underline{b}$ is a vector of recommendations about /minimum/ amounts of
 different nutrients.  Similarly, if there are some things we want to
 make sure we eat /less/ of (e.g., mercury, sodium, calories), that can
 be written as a set of linear inequalities
 \[
     Ax \leq\bar{b},
 \]
 where $\bar{b}$ is a vector of recommendations about /maximum/ amounts
 of different nutrients.  Note that this constraint can /also/ be
 expressed as a greater than constraint by multiplying both sides by $-1$.

** Linear Program
 Putting this all together, the linear program to compute the minimum
 cost diet looks like
 \[
    \min_x p'x 
 \]
 such that
 \[
    \begin{bmatrix}
       A\\
       -A
    \end{bmatrix}x \geq \begin{bmatrix}
                         \underline{b}\\
                         -\bar{b}
                       \end{bmatrix}.
 \]
  We can express this more succinctly by denoting the stacked $A$
 matrices and $b$ vectors by $\tilde{A}$ and $\tilde{b}$, respectively.


